services:
  - type: web
    name: invoice-generator-api
    env: docker
    dockerContext: .
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore # Adjust as needed
    healthCheckPath: /api/ping # Recommended for smooth deployments, though we should add a ping route if needed, or simply let Render TCP check
